### ISSUE TITLE
Java problem with unpacking message on some types of APM.

### ISSUE THREAD

**Issue by kgmormylo** [mavlink/mavlink#1020]
Hello all.
I have two APM Ardupilot mega and PX v3.
After generating java libraries i wrote some code for reading message from APM via serial port and unpack it. My PX send me sequence of message but when my app received some type of message it terminated.
First of all i have problem with msg_servo_output_raw

then it's try to perform this string this.servo9_raw = payload.getUnsignedShort();

```
MAVLINK_MSG_ID_TIMESYNC - sysid:1 compid:1 tc1:0 ts1:41795007000
msgid = 0
MAVLINK_MSG_ID_HEARTBEAT - sysid:1 compid:1 custom_mode:65536 type:13 autopilot:12 base_mode:81 system_status:3 mavlink_version:3
msgid = 4
MAVLINK_MSG_ID_PING - sysid:1 compid:1 time_usec:41838766 seq:35 target_system:0 target_component:0
msgid = 36
Exception in thread "main" java.lang.IndexOutOfBoundsException: 22
        at java.nio.HeapByteBuffer.get(Unknown Source)
        at com.MAVLink_V1.Messages.MAVLinkPayload.getUnsignedShort(MAVLinkPayload.java:77)
        at com.MAVLink_V1.common.msg_servo_output_raw.unpack(msg_servo_output_raw.java:192)
        at com.MAVLink_V1.common.msg_servo_output_raw.<init>(msg_servo_output_raw.java:226)
        at com.MAVLink_V1.MAVLinkPacket.unpack(MAVLinkPacket.java:411)
        at connection.MAVLinkRouter.onDataRecieved(MAVLinkRouter.java:43)
        at gcs.GCS.main(GCS.java:23)
```

**Comment by hamishwillee** [comment]
The field doesn't exist - so the library is correctly reporting an exception because you're attempting to index outside the array.

The field doesn't exist because you're working in MAVLink 1. If you look at the [SERVO_OUTPUT_RAW](https://mavlink.io/en/messages/common.html#SERVO_OUTPUT_RAW) message you can see that the servo 9 field is an extension message added for MAVLink 2.

You won't be able to access it using MAVLink 1 (ever).

If you want to move to MAVLink 2 you will have to use the [dronefleet](https://github.com/dronefleet/mavlink) java library as the one you are using does not support MAVLink 2 (see [supported language list](https://mavlink.io/en/#supported_languages))

**Comment by kgmormylo** [comment]
hamishwilee, thanks for comment. I guessed so. But i generate my libraries with mavgenerate, used 1.0 version for generation and xml message-definitions from github. I think it is some strange. We speak just about mavlink 1.0 only not suggesting to use mavlink 2.0. I met this behavior in some different message.

**Comment by hamishwillee** [comment]
Not a problem. Where possible you should use [MAVLink 2](https://mavlink.io/en/guide/mavlink_2.html). It is important to understand that any message with ID over 256 is MAVLink 2 ONLY, and that any field marked up in blue in the docs is also only for MAVLink2.

**Comment by kgmormylo** [comment]
Thanks hamishwillee.
