### ISSUE TITLE
Mavlink 2 translator

### ISSUE THREAD

**Issue by kuiskas** [mavlink/mavlink#1340]
Hi,
I am trying to forward message from flight control to other subsystems. FC send mavlink2, as I need for the companion. Other subsystems need Mavlink1, as they are not compatible yet. I am able to send to this if I decode every message and encode it again with the send_struct function for example:
`mavlink_msg_rc_channels_decode(&mav_msg_buf, &rc_chann_in);`
`mavlink_msg_rc_channels_send_struct(MAVLINK_COMM_1,&rc_chann_in);`
Previously I implemented:
	`mavlink_status_t* chan_state1 = mavlink_get_channel_status(MAVLINK_COMM_1);`
	`chan_state1->flags |= MAVLINK_STATUS_FLAG_OUT_MAVLINK1;`
I would like to do that without decoding the message or knowing which message I am dealing with. 
How could that be done? Is there somewhere a function for that?
I did not find a Forum for mavlink, that's why I am posing here. Hope its ok.
Any help will be appreciated.

**Comment by hamishwillee** [comment]
Support channels are listed here: https://mavsdk.mavlink.io/develop/en/index.html#getting-help

Generally the advice is to use a single protocol per channel - https://mavlink.io/en/guide/mavlink_version.html#negotiating_versions
This works because while there are some MAVLink 1 legacy components, generally they only need to communicate with just the FC.

To answer your question though, no there is no proper support for this. It is a known issue. One discussion this here: https://github.com/mavlink/mavlink/issues/1166
