### ISSUE TITLE
Installing pymavlink to system dir: INSTALL cannot set permissions/Operation not permitted.

### ISSUE THREAD

**Issue by janblumenkamp** [mavlink/mavlink#1684]
I am trying to install mavlink and mavros in a clean ROS2 workspace. Upon compiling, I get the error:
```
CMake Error at cmake_install.cmake:70 (file):
  file INSTALL cannot set permissions on
  "/usr/lib/python3.9/site-packages/pymavlink": Operation not permitted.
```
So mavlink attempts to install pymavlink to a system path, to which it obviously has no access rights. How can I work around that issue? I don't want to run colcon build with sudo and there seems to be no option to indicate that a system installation of pymavlink should be used.

**Comment by hamishwillee** [comment]
Hi @janblumenkamp

What flight stack are you using. Assuming PX4, you please repost this in https://discuss.px4.io/c/ros/38, including a link to the setup instructions that you are following. If in ArduPilot post in the discord server. It is likely that others installing this will have encountered this issue before. 

IF this proves to be a Pymavlink problem rather than a "ROS usage of Pymavlink" we would repost in https://github.com/ArduPilot/mavlink , as that is where the Pymavlink package is maintained.

Closing on assumption you are reposting and this is more of a ROS usage problem.
