### ISSUE TITLE
MAVLink Peripherals - Companion

### ISSUE THREAD

**Issue by evanatherton1** [mavlink/mavlink#1813]
Trying to forward Mavlink messages to a companion computer. Using QGroundControl v4.1.4, PX4 Pro v1.12. Set the following parameters:

MAV_1_CONFIG: TELEM2
MAV_1_MODE: Onboard
MAV_1_RATE: 80000 B/s
MAV_1_FORWARD: 1
SER_TEL2_BAUD: 921600 8N1

Is there anything else to do on the QGroundControl side? Don't seem to be receiving heartbeat messages over the serial port.

**Comment by hamishwillee** [comment]
This is not a mavlink/mavlink question - its a PX4 question. Please raise in the discussion boards or slack. 

That said, I assume you set SER_TEL<strong>1</strong>_BAUD (not SER_TEL2_BAUD) to `921600` (in order to configure 921600 8N1). The MAV forwarding looks right - that should mean anything relevant coming in from the companion computer gets forwarded to GCS and visa versa.

I assume you're connecting to PX4 to QGC. If so, are you getting the normal non-companion traffic? I.e. confirm your network connections when you raise this on the discussions.
