### ISSUE TITLE
How does Android implement the Mavlink protocol

### ISSUE THREAD

**Issue by xz971833** [mavlink/mavlink#1936]

**Comment by hamishwillee** [comment]
This area is for bugs and issues. If you need support I suggest you ask on [Discord #mavlink channel](https://discord.com/channels/1022170275984457759/1022185868317966458) or the mailing list at https://mavlink.io/en/about/support.html#support

In summary though, you use a mavlink library or SDK that will work on Android. If you want to use MAVLink libraries directly you can use any of the ones here: https://mavlink.io/en/#mavlink-project-generatorslanguages

If it were me I'd use MAVSDK https://mavsdk.mavlink.io/main/en/index.html

The reason is that mavlink libraries just send messages. Some operations require multiple messages - e.g. things like uploading missions. If you use the MAVSDK the sequences of messages are all handled for you.
