### ISSUE TITLE
Dynamic message size

### ISSUE THREAD

**Issue by DarkCowMoo** [mavlink/mavlink#1989]
Hi there,
I am new to the MAVLink protocol so be gentle.
I was wondering if using a dynamic message size is something that is supported when using Mavlink. I have some messages which size are just and few bytes and others which are much larger, while I would rather use a single message type and filter by internal ID, with dynamic size, instead of having multiple messages with different sizes. Is it possible?
Thanks

**Comment by hamishwillee** [comment]
MAVLink 2 takes whatever messages you define in a message definition, reorders them to send big fields first, then chops off any bytes that have a zero byte off the end of the message. So messages are the size of the data you specify, minus whatever can be chopped off the end because the field values are empty. That's it. 

What you are proposing is to completely go outside of MAVLink - essentially define a message with an opaque payload that you know what means, and you can extract the content. This is possible - but we don't encourage it. The only reason to do it is if you really only want to use MAVLink at all - it's just a way to get access to the channel you need for other reasons. You could look at https://mavlink.io/en/services/tunnel.html .
