### ISSUE TITLE
MAV_CMD_DO_SET_ROI is replace by MAV_CMD_DO_SET_ROI?

### ISSUE THREAD

**Issue by zyxkad** [mavlink/mavlink#2136]
At <https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI>, it says:
> MAV_CMD_DO_SET_ROI (201) — [DEP]
> DEPRECATED: Replaced By MAV*CMD_DO_SET_ROI*\* (2018-01)

Is MAV_CMD_DO_SET_ROI really deprecated? if yes, what should I use instead to rotate ardupilot?

**Comment by hamishwillee** [comment]
Deprecated means (in this case) superseded - there is an alterative that does this "better" we'd like to have implemented and used instead - in this case messages like https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI_LOCATION. However we don't track what the flight stacks do/implement.

Upshot, you will have to ask on the ardupilot forums (or test) to find out what they support. 

Note, leaving this open because "DEPRECATED: Replaced By MAVCMD_DO_SET_ROI* (2018-01)" is a typo, and this will remind me to fix that.
