### ISSUE TITLE
No asynchronous framing in mavlink? 

### ISSUE THREAD

**Issue by mkschreder** [mavlink/mavlink#632]
I would expect some kind of framing to be present if mavlink is to be used directly on top of a serial link. However including packet start sequences (0xfe) directly into the packet does not result in any escaping of these sequences. This is a serious issue and basically means that messages are missed if mavlink parser gets confused by the extra start sequences. Of course at least the wrong messages are being discarded, but this still means that mavlink itself is never 100% reliable running directly on top of a serial stream with no framing - and therefore should not be advertised as such. 

My test concludes this (I put two identical messages one after another in the buffer and start parsing using mavlink_frame_char() in the middle of the first packet. The second packet MUST be identified correctly if mavlink is to be considered reliable in this setting): 
data: 90 0xfafa
fe 03 00 00 00 64 fa fa 5a e2 c8 fe 03 00 00 00 64 fa fa 5a e2 c8 
rx: 90 0xfafa <- data of the second packet parsed out. 

With start sequence in data: 
data: 90 0xfefe
fe 03 00 00 00 64 fe fe 5a 6f d9 fe 03 00 00 00 64 fe fe 5a 6f d9 
( no parsed message here ) 

Feel free to correct me because my tests are just a result of about 1h of fiddling with it. But so far I have not seen any framing and escaping in the packets. 

Suggestion: use PPP style byte stuffed framing always when communicating directly over a serial link.

**Comment by mkschreder** [comment]
https://tools.ietf.org/html/rfc1662

**Comment by LorenzMeier** [comment]
Since MAVLink has been designed for serial links your base assumption is not correct. What is correct *with the current parser* is that if you receive a half packet you're going to loose the full length of that packet (its going to eat into the next one) plus the remaining bytes of the 2nd packet.

If you have more RAM you can actually keep a ring buffer and try to repeatedly parse the packet to overcome this (its a limitation of the implementation, not the protocol *and* the limitation is intentional to safe buffer space). In practice that's not necessary since what you are describing only happens to the first two packets in a stream of millions.

**Comment by mkschreder** [comment]
Yes but with proper framing you never need to repeatedly parse a packet.
You just need a start byte and an end byte (necessary for triggering a
parse) and to escape these bytes in the data so they never occur in the
data.

What upsets me is that not only the remaining bytes of the packet are lost
when parsing from second byte, but the next packet as well.

**Comment by mkschreder** [comment]
Feel free to use my framing implementation which is based on ppp framing.
It is tested and very lightweight. It will at most ever lose remainder of a
frame and then resync at the beginning of next frame.

Note: to not use framing on a uart connection is just asking for trouble..
