### ISSUE TITLE
Attribute error, generator fails.

### ISSUE THREAD

**Issue by vvranjek** [mavlink/mavlink#780]
When I try to generate common.xml mavlink libs (C, v2.0), generator gives a following error:
```
Errors occurred in mavgen:
Element 'field', attribute 'display':
The attribute 'display' is not allowed., line 2684
```
If I remove all the 'display' attributes, it starts complaining about all the unit attributes, such as m, s, m/s, etc..
After the removal of all unsupported attributes it generates successfully.

A bit off-topic: With which version of mavlink generator are mavlink libs generater for PX4 v1.6.5?

**Comment by magicrub** [comment]
Try this one: https://github.com/ArduPilot/pymavlink

**Comment by amilcarlucas** [comment]
well the real fix is this one https://github.com/ArduPilot/pymavlink/pull/118

**Comment by vvranjek** [comment]
Thanks, but I'm confused, is https://github.com/mavlink/mavlink/ obsolete? Why are you pointing me to an ArduPilot repo?  Is PX4 using ArduPilot's mavlink generator?

**Comment by magicrub** [comment]
The generator is part of Ardupilot. Mavlink links to it as a submodule. The ArduPilot version is the most up-to-date.

**Comment by LorenzMeier** [comment]
@vvranjek The MAVLink generator used for the standard / Dronecode is located here and is the canonical standard. For anything that is Dronecode / standard please use the repository here.

The specific issue you're having seems to be related to generating common.xml instead of standard.xml, which is what's being used to generate the standard library: https://github.com/mavlink/c_library_v2

Try that instead.

**Comment by joshlevin88** [comment]
Generating standard.xml produces the same effect.
