### ISSUE TITLE
Converting MAVLink C library to .DLL 

### ISSUE THREAD

**Issue by amvstore2018** [mavlink/mavlink#865]
Hi,
is it possible to convert MAVLink C library to .DLL using eclipse?

**Comment by amilcarlucas** [comment]
This is not a bug report, this is a question. Please post it in the support forum instead.
But the mavlink C library is an header only library generated using pymavlink from a set of .xml files (the mavlink specification), AFAIK you will need to add at least one .cpp file in order to get a .dll compiled.
