### ISSUE TITLE
Difference between GLOBAL_POSITION_INT_COV and GLOBAL_POSITION_INT

### ISSUE THREAD

**Issue by alexx600** [mavlink/mavlink#866]
I cant find detailed information about GLOBAL_POSITION_INT_COV  and GLOBAL_POSITION_INT frames.

I would like to ask if there is any difference in position (lat and long) in frames GLOBAL_POSITION_INT_COV and GLOBAL_POSITION_INT or difference is only in Covariance matrix?

**Comment by TSC21** [comment]
Those are not frames, but rather Mavlink msg types. http://mavlink.org/messages/common#GLOBAL_POSITION_INT and http://mavlink.org/messages/common#GLOBAL_POSITION_INT_COV. And yes, besides one or two fields, the main difference is the covariance matrix.

**Comment by hamishwillee** [comment]
@TSC21 Just FYI, can we start to point people towards mavlink.io instead of mavlink.org?
The mavlink.io is "better" because it is integrated with all the docs. The only difference is that the mavlink.io version may lag a change in an xml file by (max) 24 hours while mavlink.org is instantaneous. We will probably forward all links at some point.
 
https://mavlink.io/en/messages/common.html#GLOBAL_POSITION_INT
https://mavlink.io/en/messages/common.html#GLOBAL_POSITION_INT_COV

**Comment by TSC21** [comment]
> @TSC21 Just FYI, can we start to point people towards mavlink.io instead of mavlink.org?

Sure thing!

**Comment by amilcarlucas** [comment]
Can this be closed now ?
