### ISSUE TITLE
Simple working Example Client QGC with mavlink_udp.c server

### ISSUE THREAD

**Issue by JamesCordell** [mavlink/mavlink#937]
Hi

I have downloaded GCS 3.3.2 and run it with comms link udp listen on 
127.0.0.1:14550
and target host
127.0.0.1:14551

then downloaded
https://github.com/ArduPilot/mavlink.git
and
https://github.com/mavlink/c_library_v1.git
and compiled the example.
gcc -std=c99 -I ../../common -o mavlink_udp mavlink_udp.c
which compiled fine no errors.
I set under the Mavlinktab the Mavlink system ID : 1

On the console I can see the 
Bytes Received: 17
Datagram: fe 09 45 01 00 00 00 00 00 00 06 08 c0 04 03 20 33 
Received packet: SYS: 1, COMP: 0, LEN: 9, MSG ID: 0
heartbeat from GCS but I still see "Waiting for ground control station" and no data in any of the settings. What am I doing wrong?

**Comment by hamishwillee** [comment]
Hi @JamesCordell ,

According to the [example documentation](https://mavlink.io/en/getting_started/examples_scripts.html#mavlink-udp-example):

> the example sends **some data** to QGroundControl using MAVLink over UDP. *QGroundControl* responds with heartbeats and other messages, which are then printed by this program.

This is what you are seeing. The script isn't _connected_ to the ground station which is why you're getting the message. This is intentional - "connected" means "receiving heartbeats".

Note that normally you'd clone this repo (not ArduPilot, unless you need something not supported in the core). You could also build the headers rather than download them. 

Closing as not a defect.
